### ISSUE TITLE
Bundling flow with the extension

### ISSUE THREAD

**Issue by BrainMaestro** [flowtype/flow-for-vscode#113]
Currently, the extension can either use the globally installed flow binary or the one in the `node_modules` of the project. Like the way the [prettier](https://github.com/esbenp/prettier-vscode#prettier-resolution) extension handles it. This would make setup easier. Also save unnecessary installs for simple one-off projects or files

**Comment by orta** [comment]
I can see this working, but on the downside flow is pretty breaking between versions - whereas different versions of prettier have no effect on your ability to build what you're working on.

**Comment by BrainMaestro** [comment]
Yes that's a downside, but it would only affect people that decide not to use the npm packaged flow or the global one. I am not suggesting we remove those other options. This would just be a third option with the lowest priority.

**Comment by orta** [comment]
Yep, sure - makes sense, you're welcome to take a stab at it 👍

**Comment by BrainMaestro** [comment]
Sure I'll do that

**Comment by svipben** [comment]
This idea is really good, but do it like that, if there's no global or local flow (with enabled config to use from project `node_modules`) use embedded in the plugin.

**Comment by leidegre** [comment]
For the record, I think this was a mistake. It is now less clear what version of flow you are running as it's not evident what version of flow has been bundled with the extension and whether the extension is invoking the bundled version or not.

**Comment by BrainMaestro** [comment]
@leidegre. If you care about the version of your tool, you should just install flowtype locally. This defers to a locally and then globally installed flowtype before using the bundled version. Very straightforward

**Comment by leidegre** [comment]
The problem though is that it isn't self-evident which version it's picking up. A small miss step here and there and you end up with a different version than you thought and you are none the wiser. Eventually, you run into an issue you thought you've fixed to related to a specific version of flow and well, a lot of time wasted tracking down something which otherwise wouldn't be a problem.

I'm saying, while convenient, it can also create a problem and that's why I'm "officially" against this kind of thing for convenience sake.
