### ISSUE TITLE
Not all problems are recognized

### ISSUE THREAD

**Issue by svipas** [flowtype/flow-for-vscode#122]
Hello,

seems not all problems are recognized.

As you can see it doesn't show any errors.
![screenshot from 2017-04-29 22-58-26](https://cloud.githubusercontent.com/assets/10441177/25558455/d9300dd0-2d2f-11e7-837c-7cc48656d901.png)

But if I run `flow` in terminal to check for problems.
![screenshot from 2017-04-29 22-58-26 copy](https://cloud.githubusercontent.com/assets/10441177/25558460/f0ff525e-2d2f-11e7-839e-46379c531e03.png)

**Comment by vith** [comment]
Same here. Only one source segment gets highlighted when flow points at multiple places to tell you about an error.

It often highlights the type definition that is being violated rather than the instantiation where the real mistake has been made; the *Problems* tab doesn't contain the complete output either so I didn't understand why the feedback was so useless for a long time.

**Comment by remetalosse** [comment]
Same problem here.

**Comment by Mayank1791989** [comment]
Already fixed use latest plugin.
