### ISSUE TITLE
Bring new flow extension back to the community

### ISSUE THREAD

**Issue by rtorr** [flowtype/flow-for-vscode#18]
Over the last weekend, I spent my time making a [new extension named `vscode-flow`](https://github.com/rtorr/vscode-flow) for vscode to work without a dependency on the nuclide project. This new project uses the information straight from the flow tool itself. I referenced this project and the nuclide project to make sure there was usability pairing.

I want to propose that this project be moved into the flowtype namespace, or have the new code replace the code in this repository and use `flow-for-vscode` extension name. I want this to be _the one_ people install when looking for flow support, and I want the "community" to have one place to go. I would not mind being added as a maintainer of sorts.

This is in response to issue https://github.com/flowtype/flow-for-vscode/issues/12

https://github.com/rtorr/vscode-flow

**Comment by rtorr** [comment]
Basically I know there are some issues with this package, but I don't want to maintain all of it. :)

**Comment by nmote** [comment]
Sorry for letting this sit. I personally am open to this possibility but I do have to check with a few other people -- I can't make this decision myself. In particular, my manager, who is currently on vacation. So this will have to wait a bit longer, but I'm not ignoring you.

**Comment by rtorr** [comment]
@nmote no worries! Thanks for looking.

**Comment by nmote** [comment]
@rtorr Check out #19. I tend to prefer that approach since it copies Nuclide's Flow code, which seems better than solving the same problems again from scratch, and it also uses Flow to develop a Flow plugin, rather than TypeScript, which makes more sense to me. But with that said, I'm open to either one.

In any case, I've talked to my manager and we are good to go on either of these. I think we will have to replace the code in this repository and keep the license intact, though, rather than replacing the repository altogether.

Once we reach consensus I'll merge one of the PRs.

**Comment by rtorr** [comment]
@nmote I am cool with the other pull request. I did not have that much free time, but I saw mine as a way forward that did not depend on nuclide's decisions. The choice for typescript was because of vscode using it for extension documentation. 

I am ok with whatever works best! Just happy work is being done :)

**Comment by rtorr** [comment]
I am in favor of https://github.com/flowtype/flow-for-vscode/pull/19

Lets move forward with that unless we see a reason not to :)

**Comment by rtorr** [comment]
Just adding, people are using my extension. I have removed the bundled flow in the package, per suggestion.
