### ISSUE TITLE
Implement hover support

### ISSUE THREAD

**Issue by bpasero** [flowtype/flow-for-vscode#2]
I would like to leverage `FlowService.flowGetType()` for this but during build this method is lost from the export of the nuclide-flow-base node module.

**Comment by bpasero** [comment]
@nmote did you have a chance to check why flowGetType is undefined from the JS?

**Comment by nmote** [comment]
I don't think it's worth figuring that out -- instead, we should restructure nuclide-flow-base so that we don't have to transpile any of it when we consume it.

It will be straightforward to do that, but we're undergoing some major reorganizations right now so I would prefer to wait until the codebase settles down over the next couple of weeks, unless you feel that it is urgent.

**Comment by bpasero** [comment]
@nmote allright fine with me, I am happy to jump on it once that restructuring is done :)

**Comment by orta** [comment]
This is in: https://github.com/flowtype/flow-for-vscode/blob/master/lib/flowHover.js closing issue
