### ISSUE TITLE
Symbols containing $ don't quite display correctly

### ISSUE THREAD

**Issue by bsmith-cycorp** [flowtype/flow-for-vscode#319]
See here:
<img width="502" alt="browser_react_js_ _cyc-ui" src="https://user-images.githubusercontent.com/25161635/53600631-a2306500-3b6f-11e9-9fb5-43d55a166fd2.png">

Note the `$` is missing from `foo` in the hover-over.

Fortunately autocomplete and typechecking do work correctly (`$foo` will be completed with the `$` present), so it's not a huge problem

**Comment by gespispace** [comment]
Hi, can you suggest steps to repeat?
And you settings e.g. versions and settings vscode 
Because i don't get error on last version vscode and extensions.

![image](https://user-images.githubusercontent.com/37763089/53901090-e041f300-405f-11e9-8f51-0e126907f557.png)
![image](https://user-images.githubusercontent.com/37763089/53901172-1bdcbd00-4060-11e9-806a-98b52d6eee4e.png)

**Comment by bsmith-cycorp** [comment]
My Flow version is 0.83.0, so it's possible the problem lies there. Feel free to close and I'll re-open if I see it in the future after updating.

**Comment by Mayank1791989** [comment]
@bsmith-cycorp Looks like you are using `flow.useLSP: false`. Any reason why you have disabled `useLSP` mode.

**Comment by bsmith-cycorp** [comment]
I had to set it to false because otherwise it wouldn't work at all with my `.flowconfig` being anywhere other than the root of the workspace. Apologies for not mentioning that aspect.

**Comment by Mayank1791989** [comment]
@bsmith-cycorp In version `1.1.0` we have added support for `.flowconfig` anywhere in project so now there is no need to set `useLSP: false` for it.

**Comment by bsmith-cycorp** [comment]
Good to know. I'll try it out.

**Comment by bsmith-cycorp** [comment]
Confirmed that the problem is fixed when LSP is enabled.
