### ISSUE TITLE
'type' validation missing?

### ISSUE THREAD

**Issue by faeb187** [flowtype/flow-for-vscode#405]
when I declare a 'type' and use it let's say as a props parameter in React, and the parameter provide doesn't match the type, there is no warning/error, is this configurable or just missing?

Example:
`type Person = {
  name: string,
  firstName: string,
  age?: number,
}`

then let's create a person...
`const person: Person = {
  name: "John",
  age: "15"
}`

there is no warning telling me I'm using the 'type' in the wrong way... I have to check manually...

Thank you for your advice!
Kind regards, Fabio

**Comment by mroch** [comment]
flow does catch this: https://flow.org/try/#0C4TwDgpgBAChBOBnA9gOygXigbyqghgLYQBcUiw8AlqgOYA0UAZlUsAHJGnmU0NT5aEAPxlUAV0IAjBIwC+AKAUBjNBSiQkaMnC3osuAsTIAiAFLIAFqhONB3EwEYArCahygA

perhaps it's an issue with the extension not running? when you say "check manually," how are you doing that?

since this issue is old, I'm going to close but please reopen if still an issue.

**Comment by faeb187** [comment]
sorry for forgetting this one, project was just finished and I had to switch, and only checked my messages now, thanks for your support, I won't think into this again though.
