### ISSUE TITLE
Too Many Flow Extensions

### ISSUE THREAD

**Issue by ghost** [flowtype/flow-for-vscode#58]
What is the difference to the other two Flow Extensions for vscode?

**Comment by orta** [comment]
Honestly, not too sure - this project was started before both of the other extensions - and is from the flowtype org. Which is why I started contributing to this.

A quick look doesn't show any differences in features (both of the others seem to have less) - nor do they say why they were created. Perhaps it was just to scratch their own itch?

**Comment by kumarharsh** [comment]
https://github.com/flowtype/flow-for-vscode/issues/39#issuecomment-266476211

**Comment by alexdevico** [comment]
@con-ssc this extension is based on nuclide and it's supported by flowtype itself, so major flow updates can be easily ported from nuclide.

Extension from `rtorr` - `vscode-flow` comes with own version of flow binary, but it's can be outdated. Also it's have own logic with working with flow server that needs to be updated with major releases.

`vscode-flow-ide` - not sure about this, but seems that author tried to use more feaures from VSCode. For example it's shows "Flow Coverage" info for file, also some improvements to function parameters autocomplete.

**Comment by kumarharsh** [comment]
From my personal experience, `vscode-flow-ide` seems to be better feature-wise, although none of the flow modules are very good on Windows. When they work, they work well, and it's a delight to use flow, but when they don't, it becomes a nightmare. The `vscode-flow-ide`'s flow server keeps spawning 20-30 flow instances which ate up my memory and crashed my system. This extension (`flow-for-vscode`) now runs ok, but it's still sluggish sometimes. I gave up using `vscode-flow` a long time ago because it apparently stopped working - haven't checked since. These are just personal views, and I don't mean offence to the devs, who've done good job of bringing flow to vscode, but the OS support is something which can be improved upon.

**Comment by zhengying** [comment]
@kumarharsh Yes, vscode-flow-ide is better,  It's fast and not much problems , unfortunately  the project is given up, so pity...
