### ISSUE TITLE
Feature : add support to windows

### ISSUE THREAD

**Issue by Alphapage** [flowtype/flow-for-vscode#9]
Flow is implemented as alpha for windows now. It is working from command prompt globally or locally.
https://github.com/facebook/flow/issues/6?_pjax=%23js-repo-pjax-container

I tried the extension from Windows, it installs without any problem, but the file is never checked.

I haven't dig in the code, but I think flowforvscode don't use shell command and instead flowService.
Is it possible to update flow for vscode to support windows easily ?

Thanks in advance.

**Comment by nmote** [comment]
Interesting, I didn't realize Flow had any possibility of working on Windows. Right now, nuclide-flow-base short-circuits out if it detects it's running on Windows, since historically Flow has not been available. I will change that logic.

Nuclide is currently undergoing some significant turmoil so I would like to let things settle down over the next couple weeks before releasing a new version of nuclide-flow-base and in turn using it here. However I definitely intend to revisit this. This is an exciting development.

**Comment by prencher** [comment]
Any update on this?

**Comment by nmote** [comment]
I'm expecting to have some time next week or the week after to pull the Flow code out of Nuclide into a separate npm module and then update this plugin. Once that is done, fixing this issue will be straightforward.
